### ISSUE TITLE
How to serv installimage config to nodes?

### ISSUE THREAD

**Issue by bastelfreak** [virtapi/marmoset#16]
Current design: API gets stuff via /installimage/<mac>, this will be placed in the filesystem. Another webserver serves this as a static file.This makes it difficult to delete the file after it is used. Instead we could serv it via our API in a suitable format, and add something like /delete to the URL?

(CC: @sebastianrakel )

**Comment by sebastianrakel** [comment]
I added a api entpoint to get the plaintext config

```
v1/installimage/<mac>/config
```

And you can use following endpoint with the HTTP Delete method to delete configs

```
v1/installimage/<mac> 
```

Example:

```
curl -u admin:secret -X DELETE http://localhost:5000/v1/installimage/00:00:00:11
```
