### ISSUE TITLE
verify generated password after installimage

### ISSUE THREAD

**Issue by bastelfreak** [virtapi/marmoset#25]
does the generated hash actually work? sometimes the login seems to fail, we need to verify this. (also which hashing algo do we use here? a secure one?)

**Comment by bastelfreak** [comment]
what currently fails:

``` bash
curl -u admin:secret --data 'ip_address=10.30.7.41&label=archrescue' http://dhcp01.de:8080/v1/pxe
{
    "ip_address": "10.30.7.41",
    "label": "archrescue",
    "password": "FW5cdZkHAft85G1o",
    "script": null
}
```

I'm not able to login into the booted system with this password. The hash from the cmdline:

```
HASH=$6$qvmRilOYdP7ihmxO$bUDCInM8KCtcFqlSucoc0tKXZoJ/eTEznwoU4IDlISfwxhq9s2kl6oFoZna48LbHQc7a.61/MEYDZhn6q.WpB0
```

has nothing to do with the one in the shadow file

**Comment by pbyatshon** [comment]
SHA512 is used for hashing within marmorset. I reviewed the mechanism used for hash creation and password generation. That looks all fine to me, as well as the set_rootpassword function of installimage.

@bastelfreak  How does the shadow look like?

**Comment by bastelfreak** [comment]
It seems like we are providing a cmdline option with HASH=... but never really parse this and write it into our shadow file (somebody simply forgot to implement this?). I'm currently implementing this in LARS, after this is done I will check again if the provided password works. My hash in the live system in the shadow file is currently:

```
root:$6$BbwQTidj$Kl9.Pq2rkE8WzS3z11n5VvPbe20zs/IfoTE0E9NXZlwcAAAiIFQXkUQ0kMkvZMMwUxBQDVHO932VpGnRbD9Za0:14871::::::
```

this is indeed the static configured HASH during the build time of the rescue system. The LARS issue is https://github.com/virtapi/LARS/issues/25

**Comment by bastelfreak** [comment]
this issue will be open until the code is implemented in LARS so we can verify the password in our test env.

**Comment by bastelfreak** [comment]
I extended LARS to check for HASH in the cmdline and throw it into the /etc/shadow file:
https://github.com/virtapi/LARS/pull/26

this creates the following shadow entry:

``` bash
root:$6$brf9RiHlRFzfU.ao$gquqcePr0kl9refd5.aljRKdmblP68UbCB3MBJMCpm2T16vQMxibh2axZk0ZYI7awNNrxFi719GIiW4BYCI0W.:14871::::::
```

based on this cmdline:

```
BOOT_IMAGE=http://10.30.7.40/archrescue/arch/boot/x86_64/vmlinuz archiso_http_srv=http://10.30.7.40/archrescue/ archisobasedir=arch checksum=y nomodeset quiet systemd.mask=systemd-machine-id-commit systemd.mask=systemd-tmpfiles-setup systemd.mask=ldconfig initrd=http://10.30.7.40/archrescue/arch/boot/x86_64/archiso.img ip=10.30.7.41:10.30.7.40:10.30.7.1:255.255.255.128 BOOTIF=01-b8-ac-6f-97-7e-77 HASH=$6$brf9RiHlRFzfU.ao$gquqcePr0kl9refd5.aljRKdmblP68UbCB3MBJMCpm2T16vQMxibh2axZk0ZYI7awNNrxFi719GIiW4BYCI0W.
```

If I get this right, throwing the password hash into the image works. However a login is not possible, the password here is: ymTrD0N1TNwTGbdW

```
root@pxetest01.de's password: 
debug2: we sent a password packet, wait for reply
debug1: Authentications that can continue: publickey,password
Permission denied, please try again.
root@pxetest01.de's password:
```

SSH config seems to be correct, password auth is enabled. maybe the created hash is wrong? I will check that tomorrow.

**Comment by pbyatshon** [comment]
@bastelfreak that shadow entry is working correctly for me on centos7.

**Comment by bastelfreak** [comment]
awesome, so this is fixed

**Comment by pbyatshon** [comment]
it's working for you on arch as well now? Otherwise maybe the empty "mininum days required between password changes" field is a problem. At least pwck is complaining the shadow entry as invalid as long as it is empty.

```
bash-4.2# pwck -r /etc/shadow|grep root -B1
invalid password file entry
delete line 'root:$6$brf9RiHlRFzfU.ao$gquqcePr0kl9refd5.aljRKdmblP68UbCB3MBJMCpm2T16vQMxibh2axZk0ZYI7awNNrxFi719GIiW4BYCI0W.:14871::::::'? No`
```

**Comment by bastelfreak** [comment]
It doesn't work with the current hash. But we use the exact same bash code for modifying the shadow file here as we use during the creation of the image and there it works. I will debug this.

**Comment by bastelfreak** [comment]
even the normal image that we create doesn't allow me to login with a password. there seems to be some sort of issue. I modified the shadow entry a bit:

```
root:$6$OV2qalOJ$sF1PoF..gCK31249lvaASM1x7rNhDo3b61qeS4cOxeeWb/hceQNxwe3VHd5l5B6hm96Q2EqKLbQ5pxxdFybN5/:16856:0:99999:7:::
```

IMO this is a valid entry., but even now pwck complains:

``` bash
pwck -r /etc/shadow|grep root -B1
user 'root': directory '7' does not exist
```

**Comment by bastelfreak** [comment]
@pbyatshon found the issue, it was a wrong shell in `/etc/passwd`. We set the default to /usr/bin/bash, but `/etc/shells` only allows `/bin/bash` (which is an alias to `/usr/bin/bash`...)

Fix is present in https://github.com/virtapi/LARS/pull/29
