### ISSUE TITLE
Return JSON on error on /dhcp/{mac,ipv4} endpoint

### ISSUE THREAD

**Issue by bastelfreak** [virtapi/marmoset#39]
The following call:

``` bash
curl -u admin:secret http://dhcp01.example.de:8080/v1/dhcp/mac/23.45.67.8
```

returns:

```
"please provide a valid mac address"
```

the same applies for the /dhcp/ipv4 endpoint

**Comment by bastelfreak** [comment]
everywhere else we return JSON, for example [here](https://github.com/virtapi/marmoset#delete-a-record).

**Comment by sebastianrakel** [comment]
this example is shit. we have to update all repsponse objects, it will be fixed with another pull request

we should use this https://github.com/virtapi/virtapi/blob/master/docs/api/v1/general.md#response-structure

**Comment by bastelfreak** [comment]
I created two new feature requests + set a milestone for them. As discussed on IRC, we want to have this in our V2 release.
