### ISSUE TITLE
Unable to add new DHCP record to the database

### ISSUE THREAD

**Issue by bastelfreak** [virtapi/marmoset#40]
my params.json file:

``` json
{   
    "additional_statements": {}, 
    "dhcp_hostname": "pxetest01.example.de",
    "gateway": "option routers 10.30.7.1",
    "ip_address": "10.3.7.41",
    "mac": "B8:AC:6F:97:7E:77",
    "networkmask": "option subnet-mask 255.255.255.0"
}
```

API Call:

``` bash
curl -u admin:secret -X POST --data "@params.json" http://dhcp01.example.de:8080/v1/dhcp
```

returns:

``` json
{
    "message": {
        "mac": "Missing required parameter in the JSON body or the post body or the query string"
    }
}
```

**Comment by sebastianrakel** [comment]
Try this

`curl -u admin:secret --data 'ip_address=10.3.7.41&mac=B8:AC:6F:97:7E:77&gateway=10.3.7.1&networkmask=255.255.255.0' http://localhost:5000/v1/dhcp`

**Comment by bastelfreak** [comment]
``` bash
curl -u admin:secret --data 'ip_address=10.3.7.41&mac=B8:AC:6F:97:7E:77&gateway=10.3.7.1&networkmask=255.255.255.0' http://dhcp01.example.de:8080/v1/dhcp
```

returns:

```
"please provide a valid mac address"
```

---

it works if I provide the mac lowercase.

**Comment by sebastianrakel** [comment]
you should look at your code :D use lowercase chars and it should work

https://github.com/virtapi/marmoset/blob/feat-isc-dhcp/marmoset/validation.py#L6

**Comment by sebastianrakel** [comment]
The validation of mac addresses allows now upper-/lower-/mixedcase 3775e5e53bac9036321255538d5d7d420fd09d22

**Comment by sebastianrakel** [comment]
the json request part, will come with a new pull-request
