### ISSUE TITLE
Gateway parameter should be optional

### ISSUE THREAD

**Issue by ghost** [virtapi/marmoset#49]
I'm currently working on a development setup where DHCP is only used within as host-only network without any routing to outside networks and try to create a cofniguration for one VM:

 curl -u user:password --data 'ip_address=10.23.5.3&mac=08:00:27:d9:70:fa&networkmask=255.255.255.0' http://10.23.5.1:5000/v1/dhcp

This results in the following error:

{"message": "missing parameter gateway and networkmask or give an ip address in CIDR notation"}

I could work around this issue by specifying the address in CIDR notation however then it will automatically generate a gateway address:

{"dhcp_hostname": "hostname", "networkmask": "255.255.255.0", "ip_address": "10.23.5.3", "mac": "08:00:27:d9:70:fa", "gateway": "10.23.5.1", "additional_statements": {}}

In this case automatically generating the gateway is actually more harmful than helpful. Since there is now router configured, my VM will receive another gateway on the secondary NIC whilst all traffic to the outside should be routed through the primary interface which has a valid gateway set.

Since there is no requirement to have a gateway defined at all and there are many valid use cases for not having one at all, I would request the gateway parameter to be made entirely optional and the automatic generation for CIDR notations be removed or at least disabled by default.

**Comment by bastelfreak** [comment]
I didn't expect that anybody will ever use this in a network without a gateway. There are use cases where you need to enforce the gateway. We will update the code to add an option to our marmoset.conf  to enforce the gateway or make it optional, default will be enforcing.

**Comment by sebastianrakel** [comment]
@heg-hpo this only count for not CIDR notation or did you want to give a CIDR notation parameter and it will not set the gateway on its own?

**Comment by ghost** [comment]
@sebastianrakel I don't see a reason why the CIDR notation should be treated any differently. After all it's the same technical process, just another notation.

**Comment by bastelfreak** [comment]
the fix got merged
