### ISSUE TITLE
Installimage config directory is ignored

### ISSUE THREAD

**Issue by ghost** [virtapi/marmoset#50]
The sample.conf currently states that the "ConfigDirectory" parameter in the section "Config" will be used to store installimage configs. After unsuccessfully creating the directory and wondering why it wasn't used, I looked into the code and it seems that this is hardcoded to "/srv/tftp/installimage/" and the configuration parameter is not used anywhere.

I would also suggest changing the name of the section since "Config" is pretty generic and suggests some kind of global application configuration instead of options for a specific module.

**Comment by bastelfreak** [comment]
thanks for reporting this, this is a known bug that we forgot to track. It will be fixed before our 1.0 release.

**Comment by bastelfreak** [comment]
@heg-hpo this is now fixed
