### ISSUE TITLE
Extend marmoset to provide callback endpoint for the installimage

### ISSUE THREAD

**Issue by bastelfreak** [virtapi/marmoset#62]
We've got two reporting functions in our installimage:
- after an installation
- after a successful boot after an installation

We need to extend the installimage endpoint or create a new one which the installimage itself can call. In the future we want to report statistics as well (used installimage configuration). The installimage will pass the [UUID](https://github.com/virtapi/marmoset/issues/61) as an identifer. If a successful boot was reported we could remove the installimage config. The reporting endpoint needs to be configureable via our configuration file to turn it on/off. We shouldn't require any database stuff or similar if it is turned off. 

Open questions: 
- do we only rely on the UUID for authentication?
- what to do with requests from installations without UUID?
- which databaseengine do we want to use?

**Comment by bastelfreak** [comment]
@sebastianrakel I would love to hear your opinions here.

**Comment by bastelfreak** [comment]
we won't use sqlite because that will horribly fail if someone uses API + CLI at the same time.

**Comment by pbyatshon** [comment]
if we use the sqlite locking mechanism properly and dont use NFS or FAT as underlying filesystem, there should be no problem with concurrent accesses, even from different processes. So sqlite might still be an option if we want to keep it slim. 

For further details: 
https://www.sqlite.org/lockingv3.html
https://www.sqlite.org/wal.html

**Comment by bastelfreak** [comment]
Anybody has experiences with largs sqlite databases? The schema is hopefully pretty simple, but I guess we want to save information on a longer time which will result in a huge amount of data? It feels like postgres would be the better solution.

**Comment by pbyatshon** [comment]
i added a new feature branch for the possible integration of an installationstatus endpoint with sqlite as db backend. Any proposals are welcome.

What definetly needs to be clarified: What should be included in a status update? Date, status code and a status message. Anything else?

**Comment by pbyatshon** [comment]
@bastelfreak i tested with 1mio rows, couldn't recognize any problems, also when stressing the db hard with inserting thousands of entries while reading the db. Probably we won't get 10k q/s, but i guess that won't be required for marmoset ;).

**Comment by bastelfreak** [comment]
okay, sqlite will probably work. also switching to some different (R)DBMS shouldnt be that hard.

**Comment by pbyatshon** [comment]
yes, switching to a "real" database won't be much effort. I would prefer integration of an ORM like SQLAlchemy, too, but didn't used one yet, so i did it the easy way first. 

Furthermore there is no relation in the database yet, just one table. We'll have to see, what we want to add as further information. For tests i created a uuid -> id mapping table and removed the uuid from the installstatus table, but due to the lack of noticeable performance increasement with sqlite, i kept it simple and inserted all to one table.

**Comment by bastelfreak** [comment]
This got implemented in https://github.com/virtapi/marmoset/pull/87 and https://github.com/virtapi/marmoset/pull/66
