### ISSUE TITLE
Authentication on /installimage

### ISSUE THREAD

**Issue by bastelfreak** [virtapi/marmoset#63]
A client requests his config currently at v1/installimage/<his mac>/config

This requires our current htbasic auth (provided by flask). We should move that to the new authentication style that we are currently discussing in https://github.com/virtapi/marmoset/issues/62 and therefor disable basicauth on that endpoint.

**Comment by pbyatshon** [comment]
i created a feature branch for this issue. The proposal is based on a configurable whitelist for flask endpoints to bypass the authorisation. Cause authorisation is currently integrated via before_requests and therefore added for all routes a whitelist seemed easiest solution to me.
