### ISSUE TITLE
additional statements for the DHCP endpoint are not written into the ldap database

### ISSUE THREAD

**Issue by ghost** [virtapi/marmoset#75]
It is theoretically possible to add additional valid statements to the DHCP API call to write for example name servers into the DHCP configuration for a specific IP address:

```
hpo@hpo:~$ curl -u user:password --data 'ip_address=10.3.7.41&mac=00:00:00:00:00:00&gateway=10.3.7.1&networkmask=255.255.255.0&option domain-name-servers=127.0.0.1, 127.0.0.2' 127.0.0.1:5000/v1/dhcp
{
    "additional_statements": {
        "option domain-name-servers": "127.0.0.1, 127.0.0.2"
    },
    "dhcp_hostname": "dhcp01.example.com",
    "gateway": "10.3.7.1",
    "ip_address": "10.3.7.41",
    "mac": "00:00:00:00:00:00",
    "networkmask": "255.255.255.0"
}
```

The parsing of the additional statements generally seems to work since the option and the nameservers I entered are returned in the reply I receive from the server. However they are not effectively written into that database. When I request the data set again I get:

```
hpo@hpo:~$ curl -u user:password http://127.0.0.1:5000/v1/dhcp/ipv4/10.3.7.41
{
    "additional_statements": {},
    "dhcp_hostname": "dhcp01.example.com",
    "gateway": "10.3.7.1",
    "ip_address": "10.3.7.41",
    "mac": "00:00:00:00:00:00",
    "networkmask": "255.255.255.0"
}
```

The entry in the LDAP database looks like this:

```
dn: cn=10.3.7.41,cn=static,cn=DHCP Service Config,dc=example,dc=com
dhcpStatements: fixed-address 10.3.7.41;
dhcpStatements: option subnet-mask 255.255.255.0;
dhcpStatements: option routers 10.3.7.1;
objectClass: dhcpHost
dhcpComments: date=20160425_103956 dhcp-hostname=dhcp01.example.com
dhcpHWAddress: ethernet 00:00:00:00:00:00
structuralObjectClass: dhcpHost
cn: 10.3.7.41
entryUUID: f6cd74c5-04cb-4709-8242-65bbadc98de9
creatorsName: cn=root,dc=exaple,dc=com
createTimestamp: 20160425083956Z
entryCSN: 20160425083956.733138Z#000000#000#000000
modifiersName: cn=root,dc=example,dc=com
modifyTimestamp: 20160425083956Z
```

So it seems that my "option domain-name-servers" is lost somewhere between parsing the data and writing it into the database.

**Comment by ghost** [comment]
The "entry_attributes" looks like this just before the data is written to LDAP:

```
{'dhcpStatements': ['fixed-address 10.3.7.41;', 'option subnet-mask 255.255.255.0;', 'option routers 10.3.7.1;', 'option domain-name-servers 127.0.0.1, 127.0.0.2;'], 'dhcpComments': 'date=20160425_115444 dhcp-hostname=dhcp01.example.com', 'dhcpHWAddress': 'ethernet 00:00:00:00:00:00'}
```

So it seems the data is handled correctly and passed to the LDAP connection but the LDAP connection which is called with the "add" method after that doesn't know what to do with it.

**Comment by ghost** [comment]
The feature generally works. I was a bit mislead by the fact that a POST to the DHCP endpoint does not update an already existing entry. So if no entry exists, the additional statements will be written correctly. This however opens some new questions:
1. If a POST updates or overwrites an existing entry for the other endpoints, shouldn't the same work for DHCP?
2. If it is decided that a POST should not update an already existing entry, shouldn't it at least report an error?

But that's probably better discussed in a separate issue.

**Comment by bastelfreak** [comment]
for 1) We've got a few different backends here. for the installimag endpoint we save everything in textfiles and can simply overwrite that.

for2) I've created issue https://github.com/virtapi/marmoset/issues/76 to handle that.
