### ISSUE TITLE
Updating DHCP entries via PUT does not work

### ISSUE THREAD

**Issue by ghost** [virtapi/marmoset#79]
Updating an entry (identified by MAC or IP address) by doing a PUT on the respective URL does not work and ends in the following error:

```
AttributeError: 'DhcpConfig' object has no attribute 'remove'
```

The reason seems to be that "dhcp_config.remove()" is called in these methods while the "dhcp_config.remove_by_mac()" or "dhcp_config.remove_by_ipv4()" methods should be called instead as in the "delete()" method.

**Comment by bastelfreak** [comment]
fixed in https://github.com/virtapi/marmoset/pull/80
