### ISSUE TITLE
feature installimage configuration

### ISSUE THREAD

**Issue by bastelfreak** [virtapi/marmoset#8]
the installimage supports several [configuration options](https://github.com/virtapi/installimage/blob/master/functions.sh), we need a solutíon to retrieve these information via an API endpoint and we need to save them in a config file that the instalimage will fetch and parse.
- choose a config language (plain vars, ini file, yaml)
- create a new API endpoint that retrieves these information (layout?)
- create the file itself
- create a solution to automatically delete the file

**Comment by bastelfreak** [comment]
We will stay with simple $VAR='VALUE' layout so bash can easily source it (idea by @killermoehre and @bastelfreak)

**Comment by bastelfreak** [comment]
we should revalidate ini files, it is currently unclear if installimage requires variables or just KEY=Value stuff

**Comment by bastelfreak** [comment]
Further requirements:
- the stored configuration should have the same layout as the incoming values
- stored config should be parseable (= structured data)

the opinion of @sebastianrakel and @bastelfreak is that json suits best for this job. The API endpoint has to accept a json hash and will store that on the disk in a fle.

**Comment by bastelfreak** [comment]
This will be implemented in [branch issue-#8](https://github.com/virtapi/marmoset/tree/issue-%238)

hint: nobody needs json

**Comment by bastelfreak** [comment]
tested and works

**Comment by sebastianrakel** [comment]
We have no cli option! This will be implemented in the next few days

**Comment by bastelfreak** [comment]
implemented in https://github.com/virtapi/marmoset/compare/36124e76cb59...7834d2361f91
